version: "2.4"
# Start with a single host which will bootstrap the cluster. Once the
# cluster is bootstrapped we can set BOOTSTRAP_HOST and scale up
# more Consul instances.
# By using automatic bootstrapping via `-bootstrap-expect` and adding
# the environment variable, we can avoid having to use links. The
# environment variable is used once at bootstrap and then forever
# discarded by that node.
services:
  consul:
    image: mterron/consul
    read_only: true
    restart: always
    mem_limit: 128m
#    scale: 3
#    deploy:
#      mode: replicated
#      replicas: 3
    volumes:
      - /data
      - /etc/consul
    tmpfs:
      - /tmp
      - /run
    env_file: _env
    environment:
       - CONSUL_BOOTSTRAP_HOST
    cap_drop:
       - ALL
    cap_add:
       - NET_BIND_SERVICE
       - SETFCAP
       - SETUID
       - SETGID
       - CHOWN
    ports:
       - 8300
       - 8301
       - "8301/udp"
       - 8302
       - "8302/udp"
       - 8500
       - 8501
       - 8600
       - "8600/udp"
