version: "2.4"
services:
  consul:
    image: mterron/consul
    read_only: true
    restart: always
    mem_limit: 128m
    volumes:
      - /data
      - /etc/consul
      - /etc/ssl/certs
      - ${PWD}/tls:/etc/tls
      - ${PWD}/consul.json.template:/etc/consul/consul.json.template:ro
    tmpfs:
      - /tmp
      - /run
    env_file: _env
    environment:
       - CONSUL_BOOTSTRAP_HOST
    cap_drop:
       - ALL
    cap_add:
       - NET_BIND_SERVICE
       - SETFCAP
       - SETUID
       - SETGID
       - CHOWN
    ports:
       - 8300
       - 8301
       - "8301/udp"
       - 8302
       - "8302/udp"
       - 8500
       - 8501
       - 8600
       - "8600/udp"
